describe('a quality selector', () => {
    it('should be able to change the quality in all the structure links', () => {
        var playerMarkup = `<div class="av-controls"><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/0,157/quality/High" class="media-structure-uri">Lunchroom Manners</a></li><ul class="canvas-range"><a data-target="#" data-turbolinks="false" class="canvas-url" href="#avalon/time/157,178/quality/High">Getting Ready for Lunch</a><ul class="canvas-range"><a data-target="#" data-turbolinks="false" class="canvas-url" href="#avalon/time/157,178/quality/High">Washing Hands</a><ul><li class="active"><a data-turbolinks="false" data-target="#" href="#avalon/time/157,160/quality/High" class="media-structure-uri">Using Soap</a></li></ul><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/165,178/quality/High" class="media-structure-uri">Rinsing Well</a></li></ul></ul></ul><ul class="canvas-range"><a data-target="#" data-turbolinks="false" class="canvas-url" href="#avalon/time/227,378/quality/High">In the Lunchroom</a><ul class="canvas-range"><a data-target="#" data-turbolinks="false" class="canvas-url" href="#avalon/time/227,308/quality/High">At the Counter</a><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/227,245/quality/High" class="media-structure-uri">Getting Tray</a></li></ul><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/258,288/quality/High" class="media-structure-uri">Choosing Food</a></li></ul><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/301,308/quality/High" class="media-structure-uri">There will be Cake</a></li></ul></ul><ul class="canvas-range"><a data-target="#" data-turbolinks="false" class="canvas-url" href="#avalon/time/323,378/quality/High">At the Table</a><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/323,333/quality/High" class="media-structure-uri">Sitting Quietly</a></li></ul><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/362,378/quality/High" class="media-structure-uri">Eating Neatly</a></li></ul></ul></ul><ul class="canvas-range"><a data-target="#" data-turbolinks="false" class="canvas-url" href="#avalon/time/448,527/quality/High">Leaving the Lunchroom</a><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/448,492/quality/High" class="media-structure-uri">Cleaning Up</a></li></ul><ul><li><a data-turbolinks="false" data-target="#" href="#avalon/time/511,527/quality/High" class="media-structure-uri">Putting Things Away</a></li></ul></ul></ul></div>`
        var QualitySelector = require('avalon/quality-selector')
        var qualitySelector = new QualitySelector()
        var newMarkup = qualitySelector.changeQualityMarkup(playerMarkup, 'High', 'Medium')
        expect(newMarkup.search('/quality/Medium')).toBeGreaterThan(0)
        
    })
})
